export default [
  {
    accountId: 1,
    title: 'Webflow Creative Developer',
    reward: 15000,
    slug: 'Open',
    applicantCount: 128,
    referrerCount: 14,
    startsAt: new Date(),
    endsAt: new Date(),
  },
  {
    accountId: 2,
    title: 'Senior Product Designer',
    reward: 15000,
    slug: 'Pending',
    applicantCount: 128,
    referrerCount: 14,
    startsAt: new Date(),
    endsAt: new Date(),
  },
  {
    accountId: 3,
    title: 'Senior Product Designer',
    reward: 15000,
    slug: 'Archived',
    applicantCount: 128,
    referrerCount: 14,
    startsAt: new Date(),
    endsAt: new Date(),
  },
  {
    accountId: 4,
    title: 'Head of Marketing',
    reward: 15000,
    slug: 'Draft',
    applicantCount: 128,
    referrerCount: 14,
    startsAt: new Date(),
    endsAt: new Date(),
  },
  {
    accountId: 5,
    title: 'Head of Marketing',
    reward: 15000,
    slug: 'Open',
    applicantCount: 128,
    referrerCount: 14,
    startsAt: new Date(),
    endsAt: new Date(),
  },
  {
    accountId: 6,
    title: 'Head of Marketing',
    reward: 15000,
    slug: 'Open',
    applicantCount: 128,
    referrerCount: 14,
    startsAt: new Date(),
    endsAt: new Date(),
  },
  {
    accountId: 7,
    title: 'Designer-In-Residence',
    reward: 15000,
    slug: 'Open',
    applicantCount: 128,
    referrerCount: 14,
    startsAt: new Date(),
    endsAt: new Date(),
  },
  {
    accountId: 8,
    title: 'Designer-In-Residence',
    reward: 15000,
    slug: 'Open',
    applicantCount: 128,
    referrerCount: 14,
    startsAt: new Date(),
    endsAt: new Date(),
  },
];
